default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: games_tracker_development

test:
  <<: *default
  database: games_tracker_test

cypress:
  <<: *default
  database: games_tracker_cypress

production:
  url: <%= ENV['DATABASE_URL'] %>
